apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  role: kubepacs-t1-karpenter-node-role-2025112815291154130000001d
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: kubepacs-t1-k8s-cluster
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: kubepacs-t1-k8s-cluster
  amiSelectorTerms:
    - alias: al2023@latest
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
  name: default
spec:
  template:
    metadata:
      annotations:
        kubepacs.io/strategy: kubepacs
    spec:
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 5
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              cpu: 1
              memory: 1Gi
